version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: qri3adb
      POSTGRES_USER: qri3a5432
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "qri3a5432", "-d", "qri3adb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.8.0
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=myelasticpassword
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:9200 || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.8.0
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

  qri3a-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: qri3a-image
    container_name: qri3a-container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/qri3adb
      SPRING_DATASOURCE_USERNAME: qri3a5432
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      PRODUCT_IMAGES_DIR: /app/uploads/products
      # Ajout de la configuration pour Elasticsearch
      SPRING_ELASTICSEARCH_REST_URIS: http://elasticsearch:9200
    depends_on:
      - postgres
      - elasticsearch

volumes:
  postgres_data:
  elasticsearch_data:
