version: '3.8'

services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: qri3adb
      POSTGRES_USER: qri3a5432
      POSTGRES_PASSWORD: mysecretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "qri3a5432", "-d", "qri3adb"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"
    depends_on:
      - postgres

  qri3a-backend:
    build:
      context: .
      dockerfile: Dockerfile
    image: qri3a-image
    container_name: qri3a-container
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/qri3adb
      SPRING_DATASOURCE_USERNAME: qri3a5432
      SPRING_DATASOURCE_PASSWORD: mysecretpassword
      PRODUCT_IMAGES_DIR: /app/uploads/products
    depends_on:
      - postgres
volumes:
  postgres_data:
