package my.project.qri3a.enums;

public enum ProductCategory {
    // Catégories existantes
    SMARTPHONES_AND_TELEPHONES,
    TABLETS_AND_E_BOOKS,
    LAPTOPS,
    DESKTOP_COMPUTERS,
    TELEVISIONS,
    ELECTRO_MENAGE,
    ACCESSORIES_FOR_SMARTPHONES_AND_TABLETS,
    SMARTWATCHES_AND_ACCESSORIES,
    AUDIO_AND_HIFI,
    COMPUTER_COMPONENTS,
    STORAGE_AND_PERIPHERALS,
    PRINTERS_AND_SCANNERS,
    DRONES_AND_ACCESSORIES,
    NETWORK_EQUIPMENT,
    SMART_HOME_DEVICES,
    GAMING_ACCESSORIES,
    PHOTO_AND_VIDEO_EQUIPMENT,

    // Nouvelles catégories - Catégories principales
    MARKET,
    VEHICLES,
    REAL_ESTATE,

    // Nouvelles sous-catégories pour VEHICLES
    CARS,
    MOTORCYCLES,
    BICYCLES,
    VEHICLE_PARTS,
    TRUCKS_AND_MACHINERY,
    BOATS,
    OTHER_VEHICLES,

    // Nouvelles sous-catégories pour REAL_ESTATE
    REAL_ESTATE_SALES,
    APARTMENTS_FOR_SALE,
    HOUSES_FOR_SALE,
    VILLAS_RIADS_FOR_SALE,
    OFFICES_FOR_SALE,
    COMMERCIAL_SPACES_FOR_SALE,
    LAND_AND_FARMS_FOR_SALE,
    OTHER_REAL_ESTATE_FOR_SALE,
    REAL_ESTATE_RENTALS,
    APARTMENTS_FOR_RENT,
    HOUSES_FOR_RENT,
    VILLAS_RIADS_FOR_RENT,
    OFFICES_FOR_RENT,
    COMMERCIAL_SPACES_FOR_RENT,
    LAND_AND_FARMS_FOR_RENT,
    OTHER_REAL_ESTATE_FOR_RENT,

    // Catégorie par défaut pour compatibilité
    ALL_CATEGORIES,
    OTHER_CATEGORIES
}