package my.project.qri3a.enums;

public enum ProductCategory {
    SMARTPHONES_AND_TELEPHONES,
    TABLETS_AND_E_BOOKS,
    LAPTOPS,
    DESKTOP_COMPUTERS,
    GAMING,
    GADGETS,
    TELEVIZIONS,
    CAMERAS,
    AIRPODS_AND_HEADPHONES,
    OTHER_ELECTRONIC_MATERIALS,
    ACCESSORIES_FOR_SMARTPHONES_AND_TABLETS,
    SMARTWATCHES_AND_ACCESSORIES,
    AUDIO_AND_HIFI,
    COMPUTER_COMPONENTS,
    STORAGE_AND_PERIPHERALS,
    PRINTERS_AND_SCANNERS,
    DRONES_AND_ACCESSORIES,
    NETWORK_EQUIPMENT,
    SMART_HOME_DEVICES,
    GAMING_ACCESSORIES,
    PHOTO_AND_VIDEO_EQUIPMENT,
    AUDIO_ACCESSORIES,
    COMPUTER_ACCESSORIES,
    NEW_ARRIVALS
}